---
 
- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: ubuntu,apache,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: install apache and php for CentOS servers
    tags: rocky,httpd,php
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Rocky"]
