---

- hosts: all
  become: true

  tasks:
    - name: update linux index, install apache and php
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
