---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS","Rocky"]

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]


- hosts: web_server
  become: true
  tasks:

  - name: install httpd package (CentOS)
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS", "Rocky"]

  - name: install apache2 package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: copy html file to apache/httpd directory
    tags: apache, html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb server package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS", "Rocky"]

  - name: install mariadb server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu"]

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
