---

- hosts: workstation
  become: true
  tasks:
    - name: update ubuntu index
      apt:
        update_cache: yes

    - name: install unzip package
      package:
        name: unzip

    - name: install terraform package
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0644
